### ISSUE TITLE
Implementar Autenticación con JWT (Web y Mobile)

### ISSUE THREAD

**Issue by Tincho44** [Tincho44/Proyecto-Final-DWM#2]
Subtareas:

- Crear formularios de login y registro.
- Integrar autenticación con JWT (almacenamiento y manejo del token).
- Proteger rutas privadas en la aplicación.
- Implementar logout.

**Comment by FacumendezBT** [comment]
Pronto en main!
![image](https://github.com/user-attachments/assets/ce1a33d4-ad03-4853-98d4-d3d0cd049bbd)
